on: push
name: ShellCheck
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: shellcheck
      uses: ludeeus/action-shellcheck@master
      with:
        args: -e SC1091
